-auth	[success=2 default=ignore]	pam_fprintd.so	max-tries=3 timeout=300
auth       [success=1 default=bad]     pam_unix.so          try_first_pass nullok likeauth
auth       [default=die]               pam_faillock.so      authfail
auth       optional                    pam_permit.so
